# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'food_identity_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

import cv2
import tensorflow as tf
from PIL import Image
import numpy as np
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap


class Ui_MainWindow(object):
    img_src = 'E:\pythonTest\\ve_test\\vegetables_tf2.3-master\GUI\img\\food_example.png'
    resnet_model = tf.keras.models.load_model("../models/resnet_foot_easy.h5")
    class_name = ['苹果派', '鸡翅', '巧克力蛋糕', '甜甜圈', '菲力牛排', '年糕', '饺子', '汉堡包', '热狗', '冰淇淋']

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1080, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1080, 720))
        MainWindow.setMaximumSize(QtCore.QSize(1080, 720))
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(420, 50, 271, 41))
        self.label.setStyleSheet("font: 22pt \"黑体\";\n"
"color: rgb(78, 110, 242);")
        self.label.setObjectName("label")
        self.picture_btn = QtWidgets.QPushButton(self.centralwidget)
        self.picture_btn.setGeometry(QtCore.QRect(60, 580, 131, 41))
        self.picture_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.picture_btn.setStyleSheet("#picture_btn{\n"
"font: 11pt \"黑体\";\n"
"color: #fff;\n"
"background-color: #4e6ef2;\n"
"border:none;\n"
"border-radius:6px;\n"
"}\n"
"#picture_btn:hover{\n"
"background-color:#4662d9;\n"
"}")
        self.picture_btn.setObjectName("picture_btn")
        self.img_box = QtWidgets.QLabel(self.centralwidget)
        self.img_box.setGeometry(QtCore.QRect(50, 150, 481, 381))
        self.img_box.setStyleSheet("background-image: url(\"https://ai.bdstatic.com/file/59915F3F62BF4D9B8CF845B2F929279F\");\n"
"image: url(\"https://ai.bdstatic.com/file/59915F3F62BF4D9B8CF845B2F929279F\");")
        self.img_box.setText("")
        self.img_box.setObjectName("img_box")
        self.img_box.setPixmap(QPixmap(self.img_src))
        self.img_box.setScaledContents(True)
        self.identity_btn = QtWidgets.QPushButton(self.centralwidget)
        self.identity_btn.setGeometry(QtCore.QRect(370, 580, 131, 41))
        self.identity_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.identity_btn.setStyleSheet("#identity_btn{font: 11pt \"黑体\";\n"
"color: #fff;\n"
"background-color: #4e6ef2;\n"
"border:none;\n"
"border-radius:6px;\n"
"}\n"
"#identity_btn:hover{\n"
"background-color:#4662d9;\n"
"}")
        self.identity_btn.setObjectName("identity_btn")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(640, 550, 381, 121))
        self.groupBox.setStyleSheet("")
        self.groupBox.setObjectName("groupBox")
        self.result_label = QtWidgets.QLabel(self.groupBox)
        self.result_label.setGeometry(QtCore.QRect(80, 50, 271, 41))
        self.result_label.setText("")
        self.result_label.setObjectName("result_label")
        self.result_icon = QtWidgets.QLabel(self.groupBox)
        self.result_icon.setGeometry(QtCore.QRect(20, 50, 41, 41))
        self.result_icon.setText("")
        self.result_icon.setObjectName("result_icon")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(640, 300, 381, 201))
        self.groupBox_2.setObjectName("groupBox_2")
        self.mix_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.mix_btn.setGeometry(QtCore.QRect(30, 60, 131, 41))
        self.mix_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mix_btn.setStyleSheet("#mix_btn{font: 11pt \"黑体\";\n"
"color: #fff;\n"
"background-color: #4e6ef2;\n"
"border:none;\n"
"border-radius:6px;\n"
"}\n"
"#mix_btn:hover{\n"
"background-color:#4662d9;\n"
"}")
        self.mix_btn.setObjectName("mix_btn")
        self.error_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.error_btn.setGeometry(QtCore.QRect(220, 60, 131, 41))
        self.error_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.error_btn.setStyleSheet("#error_btn{font: 11pt \"黑体\";\n"
"color: #fff;\n"
"background-color: #4e6ef2;\n"
"border:none;\n"
"border-radius:6px;\n"
"}\n"
"#error_btn:hover{\n"
"background-color:#4662d9;\n"
"}")
        self.error_btn.setObjectName("error_btn")
        self.loss_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.loss_btn.setGeometry(QtCore.QRect(30, 130, 131, 41))
        self.loss_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.loss_btn.setStyleSheet("#loss_btn{font: 11pt \"黑体\";\n"
"color: #fff;\n"
"background-color: #4e6ef2;\n"
"border:none;\n"
"border-radius:6px;\n"
"}\n"
"#loss_btn:hover{\n"
"background-color:#4662d9;\n"
"}")
        self.loss_btn.setObjectName("loss_btn")
        self.other_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.other_btn.setGeometry(QtCore.QRect(220, 130, 131, 41))
        self.other_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.other_btn.setStyleSheet("#other_btn{font: 11pt \"黑体\";\n"
"color: #fff;\n"
"background-color: #4e6ef2;\n"
"border:none;\n"
"border-radius:6px;\n"
"}\n"
"#other_btn:hover{\n"
"background-color:#4662d9;\n"
"}")
        self.other_btn.setObjectName("other_btn")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(650, 130, 351, 141))
        self.label_3.setStyleSheet("color: rgb(153, 153, 153);\n"
"font:18px;")
        self.label_3.setObjectName("label_3")
        self.title_icon = QtWidgets.QLabel(self.centralwidget)
        self.title_icon.setGeometry(QtCore.QRect(360, 50, 41, 41))
        self.title_icon.setText("")
        self.title_icon.setObjectName("title_icon")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Resnet食品识别"))
        self.picture_btn.setText(_translate("MainWindow", "选择图片"))
        self.identity_btn.setText(_translate("MainWindow", "开始识别"))
        self.groupBox.setTitle(_translate("MainWindow", "识别结果"))
        self.groupBox_2.setTitle(_translate("MainWindow", "功能"))
        self.mix_btn.setText(_translate("MainWindow", "展示混淆矩阵"))
        self.error_btn.setText(_translate("MainWindow", "错分类样本"))
        self.loss_btn.setText(_translate("MainWindow", "损失函数"))
        self.other_btn.setText(_translate("MainWindow", "其他数据"))
        self.label_3.setText(_translate("MainWindow", "可识别包括热狗，饺子，冰淇淋等十种食物，\n"
"返回识别的食物名称，并有混淆矩阵和错分\n"
"类样本等相关数据展示"))
        self.mix_btn.clicked.connect(self.show_mix)
        self.error_btn.clicked.connect(self.show_error)
        self.loss_btn.clicked.connect(self.show_loss)
        self.picture_btn.clicked.connect(self.select_img)
        self.identity_btn.clicked.connect(self.predict_img)
        self.other_btn.clicked.connect(self.other_data)

    def show_mix(self):
        self.img_src='E:\pythonTest\\ve_test\\vegetables_tf2.3-master\GUI\data_img\\resnet_heatmap1.png'
        self.img_box.setPixmap(QPixmap(self.img_src))
    def show_error(self):
        self.img_src='E:\pythonTest\\ve_test\\vegetables_tf2.3-master\GUI\data_img\\resnet_error_img.png'
        self.img_box.setPixmap(QPixmap(self.img_src))
    def show_loss(self):
        self.img_src='E:\pythonTest\\ve_test\\vegetables_tf2.3-master\GUI\data_img\\results_resnet.png'
        self.img_box.setPixmap(QPixmap(self.img_src))
    def other_data(self):
        self.img_src = 'E:\pythonTest\\foot_identity\GUI\data_img\\APR.png'
        self.img_box.setPixmap(QPixmap(self.img_src))
    def select_img(self):
        directory = QtWidgets.QFileDialog.getOpenFileName(None, "选取图片", "./", "*.png , *.jpg")  # 起始路径
        if directory[0] != '':
            self.img_src = directory[0]
            self.img_box.setPixmap(QPixmap(self.img_src))

    def predict_img(self):
        img = cv2.imread(self.img_src)
        img_init = cv2.resize(img, (224, 224))
        cv2.imwrite('target.png', img_init)
        img = Image.open('target.png')  # 读取图片
        img = np.asarray(img)  # 将图片转化为numpy的数组
        outputs = self.resnet_model.predict(img.reshape(1, 224, 224, 3))  # 将图片输入模型得到结果
        result_index = int(np.argmax(outputs))
        result = self.class_name[result_index]
        self.result_label.setText('识别结果为：'+result)



